name: "Re-trigger Workflows on open PRs"

on:
  push:
    branches: [main]

jobs:
  retrigger-workflows-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: tiagobento/retrigger-workflows-on-open-prs@0.1.1
        with:
          github_token: ${{ secrets.KOGITO_TOOLING_BOT_TOKEN }}
